export enum NotificationTypes {
  JOIN_TEAM = 1,
  JOIN_TOURNAMENT = 2,
  CHALLENGE_TEAM = 3,
  LEAVE_TEAM = 4,
  REQUEST_TO_JOIN_TEAM = 5,
  REQUEST_TO_JOIN_TOURNAMENT = 6,
  EDOT_TOURNAMENT_MATCHES = 7,
  LEAVE_TOURNAMENT = 8,
  ALERT = 9,
}
